### ISSUE TITLE
[Idea]: Чмоня

### ISSUE THREAD

**Issue by HappyExclave** [DemonWayne/Issues#1]
### Выберите проект в который хотите предложить идею

MS bot

### Опишите идею

Добавить на серверер ручного чмоню. Который будет помагать всем.

### Доп. Информация

не требуется

**Comment by DemonWayne** [comment]
![image](https://user-images.githubusercontent.com/80221813/161005618-9e00e2fb-6d5d-430e-9048-310aeff8682e.png)
Добавлено.

**Comment by HappyExclave** [comment]
АХХААХАХАХ СПАСИБО ДЯДЯ!

**Comment by DemonWayne** [comment]
Открыто
